/* eslint-disable @next/next/no-img-element */
import Layout from '@/components/layout/layout';
import Section from '@/components/layout/section';
import Link from '@/components/link/link';
import EarthCanvas from '@/components/three/earth';
import Head from 'next/head';
import Image from 'next/image';
import { MdOutlineKeyboardArrowRight } from 'react-icons/md';

export default function Home() {
  return (
    <>
      <Head>
        <title>MNR</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/title.ico' />
      </Head>
      <Layout>
        <Section size='small' flex>
          <div>
            <h1 className='font-secondary text-[40px] font-bold'>
              Naufal Rafianto
            </h1>
            <p className='font-sm'>Freelance Developer (Website / Mobile)</p>
          </div>
          <div className='h-32 w-32 flex-shrink-0 cursor-pointer overflow-hidden rounded-full border-2 border-white hover:opacity-75 max-md:h-24 max-md:w-24'>
            <Image
              src='/images/image-profile.jpg'
              alt='profile image'
              width={128}
              height={128}
              className='h-full w-full object-cover'
            />
          </div>
        </Section>
        <Section size='medium'>
          <h1 className='relative mb-5 ml-5 w-fit cursor-pointer text-start text-lg font-bold uppercase after:absolute after:bottom-0 after:left-0 after:h-1 after:w-full after:bg-accent after:bg-opacity-50 after:hover:bg-opacity-100'>
            About Me
          </h1>
          <p className='mx-auto w-[90%] text-justify font-extralight'>
            Hi there! I&apos;m Naufal, a freelance developer based on Indonesia.
            As a freelance web and mobile developer with one year of experience,
            I am passionate about crafting high-quality applications that meet
            my client&apos;s needs. I have a solid foundation in web development
            technologies such as{' '}
            <span className='text-accent'>
              {' '}
              HTML, CSS, JavaScript, ReactJS, TailwindCSS, NextJS, NodeJS{' '}
            </span>
            etc. As well as experience in mobile app development using{' '}
            <span className='text-accent'>React Native</span>. I am constantly
            learning and keeping up-to-date with the latest trends and best
            practices in the industry.
          </p>
          <div className='flex justify-center'>
            <Link
              href='https://www.linkedin.com/in/naufal-rafianto-4159a8206/'
              isButton
            >
              My LinkedIn
              <MdOutlineKeyboardArrowRight fontSize={24} />
            </Link>
          </div>
        </Section>
      </Layout>
    </>
  );
}
