import '@/styles/globals.css'
import { Prompt } from 'next/font/google'
import * as React from 'react'

const font = Prompt({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    )
}
